name: Harshit Kumar
email: kumar_harshit@outlook.com
description: Technical Fridays - personal website and blog
url: https://kHarshit.github.com
github_username: kHarshit
twitter_username: harshit_kumar1

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title


# Google services
google_analytics: UA-103268503-1


gems:
  - jekyll-feed
  - jekyll-sitemap  # sitemap at /sitemap.xml
